_BASE_: "./vpt_base.yaml"
#
#
# ----------------------------------------------------------------------
# Solver options
# ----------------------------------------------------------------------
#
#
SOLVER:
  OPTIMIZER: "sgd"
  LEARNING_RATE: 0.1
  WEIGHT_DECAY: 0.00001
  WARMUP_EPOCHS: 5
  LAST_EPOCH: 75
#
#
# ----------------------------------------------------------------------
# Dataset options
# ----------------------------------------------------------------------
#
#
DATASET:
  NAMES : ["CheXpert", "MIMIC_CXR"]
  SUBSET : "BLACK"
  PATHS : ["data/datasets/chexpert/BLACK/", "data/datasets/mimic_cxr/BLACK/"]
  DATA_PATHS : ["/path/to/chexpert/", "/path/to/chexpert/"]
  BATCH_SIZE : 128
#
#
# ----------------------------------------------------------------------
# END
# ----------------------------------------------------------------------
#
#