_BASE_: "./linear_base.yaml"
#
#
# ----------------------------------------------------------------------
# Model options
# ----------------------------------------------------------------------
#
#
MODEL:
  SAVE_FREQUENCY: 1
  PRETRAINED_DATASET: "imagenet"
  BACKBONE_PATH: "./data/input/imagenet_pretrained_mae_vitb.pth"
#
#
# ----------------------------------------------------------------------
# Solver options
# ----------------------------------------------------------------------
#
#
SOLVER:
  OPTIMIZER: "sgd"
  LEARNING_RATE: 0.1
  WEIGHT_DECAY: 0.00001
  WARMUP_EPOCHS: 5
  LAST_EPOCH: 75
#
#
# ----------------------------------------------------------------------
# Dataset options
# ----------------------------------------------------------------------
#
#
DATASET:
  NAMES : ["CheXpertMAE", "MIMIC_CXR_MAE"]
  SUBSET : "ASIAN"
  PATHS : ["data/datasets/chexpert/ASIAN/", "data/datasets/mimic_cxr/ASIAN/"]
  DATA_PATHS : ["/path/to/chexpert/", "/path/to/chexpert/"]
  BATCH_SIZE : 128
#
#
# ----------------------------------------------------------------------
# END
# ----------------------------------------------------------------------
#
#