_BASE_: "../../base.yaml"
#
#
# ----------------------------------------------------------------------
# General options
# ----------------------------------------------------------------------
#
#
OUTPUT_DIR : "./data/output/"
#
# ----------------------------------------------------------------------
# Model options
# ----------------------------------------------------------------------
#
#
MODEL:
  SAVE_FREQUENCY: 1
  NAME: "E2VPT_MoCoV3"
  ARCH: "vit_base"
#
#
# ----------------------------------------------------------------------
# Transfer learning options
# ----------------------------------------------------------------------
#
#
  E2VPT:
    KV_PROMPT:
      MASK_CLS_TOKEN : True
      NUM_TOKENS_P: 10
#
#
# ----------------------------------------------------------------------
# END
# ----------------------------------------------------------------------
#
#