_BASE_: "../../base.yaml"
#
#
# ----------------------------------------------------------------------
# General options
# ----------------------------------------------------------------------
#
#
OUTPUT_DIR : "./data/output/"
#
# ----------------------------------------------------------------------
# Model options
# ----------------------------------------------------------------------
#
#
MODEL:
  SAVE_FREQUENCY: 1
  NAME: "Linear_MAE"
  ARCH: "vit_base"
#
#
# ----------------------------------------------------------------------
# END
# ----------------------------------------------------------------------
#
#