_BASE_: "./full_base.yaml"
#
#
# ----------------------------------------------------------------------
# Model options
# ----------------------------------------------------------------------
#
#
MODEL:
  SAVE_FREQUENCY: 1
  PRETRAINED_DATASET: "chestxray"
  BACKBONE_PATH: "./data/input/mocov3_chexpert_mimic_cxr_pre300.pth.tar"
#
#
# ----------------------------------------------------------------------
# Solver options
# ----------------------------------------------------------------------
#
#
SOLVER:
  OPTIMIZER: "sgd"
  WARMUP_EPOCHS: 10
  LAST_EPOCH: 100
#
#
# ----------------------------------------------------------------------
# Dataset options
# ----------------------------------------------------------------------
#
#
DATASET:
  NAMES : ["ChestXRayVTAB"]
  SUBSET : "ALL"
  PATHS : ["data/datasets/chestxray_vtab/CheXpert-MIMIC_CXR/"]
  DATA_PATHS : [""]
  BATCH_SIZE : 64
#
#
# ----------------------------------------------------------------------
# END
# ----------------------------------------------------------------------
#
#