_BASE_: "./gvpt_base.yaml"
#
#
# ----------------------------------------------------------------------
# Model options
# ----------------------------------------------------------------------
#
#
MODEL:
  SAVE_FREQUENCY: 1
  PRETRAINED_DATASET: "imagenet"
  BACKBONE_PATH: "./data/input/imagenet_pretrained_mocov3_vitb_300ep.pth.tar"
#
#
# ----------------------------------------------------------------------
# Solver options
# ----------------------------------------------------------------------
#
#
SOLVER:
  OPTIMIZER: "sgd"
  LEARNING_RATE: 0.1
  WEIGHT_DECAY: 0.00001
  WARMUP_EPOCHS: 5
  LAST_EPOCH: 75
#
#
# ----------------------------------------------------------------------
# Dataset options
# ----------------------------------------------------------------------
#
#
DATASET:
  NAMES : ["CheXpertMoCoV3", "MIMIC_CXR_MoCoV3"]
  SUBSET : "WHITE"
  PATHS : ["data/datasets/chexpert/WHITE/", "data/datasets/mimic_cxr/WHITE/"]
  DATA_PATHS : ["/path/to/chexpert/", "/path/to/chexpert/"]
  BATCH_SIZE : 128
#
#
# ----------------------------------------------------------------------
# END
# ----------------------------------------------------------------------
#
#