_BASE_: "./e2vpt_base.yaml"
#
#
# ----------------------------------------------------------------------
# Solver options
# ----------------------------------------------------------------------
#
#
SOLVER:
  OPTIMIZER: "sgd"
  LEARNING_RATE: 0.1
  WEIGHT_DECAY: 0.00001
  WARMUP_EPOCHS: 10
  LAST_EPOCH: 100
#
#
# ----------------------------------------------------------------------
# Dataset options
# ----------------------------------------------------------------------
#
#
DATASET:
  NAMES: ["FemaleCelebA"]
  SUBSET: "FEMALE"
  PATHS: ["/datasets/celeba_pytorch/celeba/"]
  DATA_PATHS: ["/datasets/celeba_pytorch/celeba/img_align_celeba/"]
  BATCH_SIZE: 64
#
#
# ----------------------------------------------------------------------
# END
# ----------------------------------------------------------------------
#
#