_BASE_: "../../base.yaml"
#
#
# ----------------------------------------------------------------------
# General options
# ----------------------------------------------------------------------
#
#
OUTPUT_DIR : "./data/output/"
#
# ----------------------------------------------------------------------
# Model options
# ----------------------------------------------------------------------
#
#
MODEL:
  SAVE_FREQUENCY: 1
  NAME: "Full_ViT"
  ARCH: "vit_base"
  PRETRAINED_DATASET: "imagenet"
  BACKBONE_PATH: "./data/input/imagenet_vitb.npz"
#
#
# ----------------------------------------------------------------------
# Transfer learning options
# ----------------------------------------------------------------------
#
#
  E2VPT:
    KV_PROMPT:
      MASK_CLS_TOKEN : True
      NUM_TOKENS_P: 10
#
#
# ----------------------------------------------------------------------
# END
# ----------------------------------------------------------------------
#
#